---
- name: remove  old installation if it's needed.
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/consul.service
    - /usr/share/consul
    - /var/consul.d
  notify: sysd_restart
  tags: reset_consul

- name: echo de la version enregistree 
  debug:
    msg: "{{ lookup('consul_kv', 'consul_check_version', host=item, port='8500') }}"
  loop:
    - "{{ master1 }}"
  register: actual_version

- name: Launch all tasks if consul version is different or not installed
  block: 
    - name: Ensure group "consul" exists
      group:
        name: "{{ consul_group }}"
        state: present
    - name: create user 
      user:
        name: consul
        groups: root, consul

    - name: create consul user
      user:
        name: "{{ consul_user }}"
        comment: Consul user
        shell: /bin/bash
        group: "{{ consul_group }}"
        groups: "root,{{ consul_group }}"

    - name: packages requirments
      include_tasks: requirments.yml

    - name: install set dnsmasq to pass the 8600 discovery port
      include_tasks: dnsmasq.yml

    - name: install Consul & Dependencies
      include_tasks: install_consul.yml

    - name: Configure folder for Consul
      include_tasks: configure.yml
      
    - name: configure systemd
      include_tasks: service.yml
      
    - name: Configure folder for Consul
      include_tasks: test.yml
  when: actual_version != "{{ consul_version }}"