- name: Create systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/consul.service
    owner: consul 
    group: consul
    mode: 0644

- name: enable the service
  systemd: 
    state: started
    daemon_reload: yes
    enabled: yes
    name: consul